#!/usr/bin/perl

#use diagnostics -verbose;
use DBI;
use Net::OpenSSH::Parallel;
use DateTime;

                                                   ####Log-in to MySQL and pull the active proxies####
{
           my $user = "db_user";
           my $pw = "";
           my $database = "new_mail";
           my $host = "masterdb.routename.com";
           my $dsn = "DBI:mysql:$database:$host";

       my $connect =  DBI->connect($dsn, $user, $pw)
                      or die "Uh oh! MySql's not connecting :( " .$DBI::errstr ."\n";

           my $sql = $connect->prepare("SELECT managementIP
                                          FROM Server s, ProxyGroupServer pgs
                                         WHERE s.active=1 AND s.serverID=pgs.serverID");

              $sql->execute() or die "mysql no worky:" .$sql->errstr();
                 print "Total Active Proxies:" .$sql->rows ."\n";

                                                   #####Log-in to each proxy, rsync files and restart httpd####

              while (@proxy = $sql->fetchrow_array ){
                         my $date = DateTime->from_epoch( epoch => time );
                         my $failures = "failures.txt";
                foreach my $active (@proxy) {
                         $ssh = Net::OpenSSH->new("root@" .$active);
                         my @rsync = $ssh->rsync_put({glob => 1}, '/etc/httpd/conf/httpd.conf','/etc/httpd/conf/httpd.conf') #rsync_put(%opts,local,remote)
                                           or print "rsync no worky:$active\n"
                                           and open FAIL, '>>', $failures
                                           and print FAIL "rsync fail on $active " .$date->mdy('/')." " .$date->hms ."\n";
                                    system @rsync;    #not sure why this get's an error, rsyncs fine
                          my @httpd = $ssh->make_remote_command('service httpd restart')
                                           or print "httpd noooooo\n"
                                           and open FAIL, '>>', $failures
                                           and print FAIL "httpd fail on $active " .$date->mdy('/') ." " .$date->hms ."\n";
                                   system @httpd;

             }


          close FAIL;

}


}


                                                                                                                       #By Christina: ccoleman@zetainteractive.com#

